<div class="addon">
    <div class="features">
        
        <h2> Company list</h2>
            <?php for($i=1;$i<=5;$i++){
            echo 
            '<div class="row">
                <div class="span1">
                    <div class="features-image">
                        <div>
                            <div class="thumbnail-content">
                                <img class="member-photo" width="60" height="60" alt="Se som" src="http://m.c.lnkd.licdn.com/mpr/mpr/shrink_80_80/p/1/000/215/34a/2b11a81.jpg">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="features-desc">
                        <div class="short-desc">Quick and Easy sale process</div>
                        <table>
                             <tbody>
                    <tr>
                        <th>Name</th>
                        <td>
                            <a href="/?filter=%7B%22order_by%22%3A+%22click_counter+desc%22%2C+%22author%22%3A+28%7D">OpenERP SA</a>
                        </td>
                    </tr>
                    <tr>
                        <th>Company name</th>
                        <td>
                            <a href="/?filter=%7B%22order_by%22%3A+%22click_counter+desc%22%2C+%22author%22%3A+28%7D">OpenERP SA</a>
                        </td>
                    </tr>
                    <tr>
                        <th>Telephone</th>
                        <td>
                            <a href="/?filter=%7B%22order_by%22%3A+%22click_counter+desc%22%2C+%22author%22%3A+28%7D">OpenERP SA</a>
                        </td>
                    </tr>
                </tbody>
                        </table>
                    </div>
                </div>
                </div>'; }?>
        
            <div class="clear-both"></div>
    </div>
</div>