<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>HTML5 Contact Form</title>
    <link rel="stylesheet" media="screen" href="styles.css" >
</head>
<body>
    <form class="contact_form" action="" method="post" name="contact_form">
        <ul>
    <li>
         <h2>Contact Us</h2>
         <span class="required_notification">* Denotes Required Field</span>
    </li>
    <li>
        <label for="name">Name:</label>
        <input type="text" name="name" />
    </li>
    <li>
    <label for="email">Email:</label>
    <input type="text" name="email" />
    <span class="form_hint">Proper format "name@something.com"</span>
</li>
</ul>
    </form>
</body>
</html>