
<script type="text/javascript" src="http://platform.linkedin.com/in.js">
  api_key: jfzqnuuz7z00
  onLoad: onLinkedInLoad
  scope: r_fullprofile,r_basicprofile
</script>

<input type="hidden">

<!-- NOTE: be sure to set onLoad: onLinkedInLoad -->
<script type="text/javascript">
function onLinkedInLoad() {
  IN.Event.on(IN, "auth", function() {onLinkedInLogin();});
  IN.Event.on(IN, "logout", function() {onLinkedInLogout();});
}
setLoginBadge(true);
alert(j+","+k);
function onLinkedInLogout() {
  setLoginBadge(false);
}

function onLinkedInLogin() {
  // we pass field selectors as a single parameter (array of strings)
  IN.API.Profile("me")
    .fields(["id", "firstName", "lastName","dateOfBirth","positions:(title,summary,startDate,endDate,company:(name))",
             "educations:(schoolName,fieldOfStudy,startDate,endDate,degree,activities,notes)","pictureUrl",
             "interests"])
    .result(function(result) {
      setLoginBadge(result.values[0]);
    })
    .error(function(err) {
      alert(err);
    });
}

function setLoginBadge(profile) {
     pos_title = new Array();
     pos_company = new Array();
     pos_date = new Array();
     pos_summary = new Array();
     edu_schoolName = new Array();
     edu_fieldOfStudy = new Array();
     edu_date = new Array();
     edu_degree = new Array();
     edu_activities = new Array();
     edu_notes = new Array();
    id = profile.id;
    last_name = profile.last_name;
    first_name = profile.first_name;
    dateOfBirth = profile.dateOfBirth.day+"-"+profile.dateOfBirth.month+"-"+profile.dateOfBirth.year;
  if (!profile) {
    profHTML = "<p>You are not logged in</p>";
  }
  else {
    
     j=profile.positions._total;
     k=profile.educations._total;
    for (var i=0;i<j;i++){
        
        pos_title[i] = profile.positions.values[i].title;
        pos_company[i] = profile.positions.values[i].company.name;
        //alert(profile.positions.values[0].endDate);
        if((profile.positions.values[i].startDate == null)&&(profile.positions.values[i].endDate != null)){
            pos_date[i]="FROM <i>Unknow</i> TO <i>"+profile.positions.values[i].endDate.month +"-"+profile.positions.values[i].endDate.year +"</i>";
        }else if((profile.positions.values[i].startDate != null)&&(profile.positions.values[i].endDate == null)){
             pos_date[i]="FROM <i>"+ profile.positions.values[i].startDate.month +"-"+ profile.positions.values[i].startDate.year+"</i> TO <i>Unknow</i>";
        }else if((profile.positions.values[i].startDate != null)&&(profile.positions.values[i].endDate != null)){
            pos_date[i]="FROM <i>"+ profile.positions.values[i].startDate.month +"-"+ profile.positions.values[i].startDate.year+"</i> To <i>"+profile.positions.values[i].endDate.month +"-"+profile.positions.values[i].endDate.year+"</i>";
        }else{
            pos_date[i]="<i>Unknow</i>";
        }
        pos_summary[i] = profile.positions.values[i].summary;
        
    }
    //education
    for(var i=0;i<k;i++){
        edu_schoolName[i] = profile.educations.values[i].schoolName;
        edu_fieldOfStudy[i] =profile.educations.values[i].fieldOfStudy;
        
        if((profile.educations.values[i].startDate == null)&&(profile.educations.values[i].endDate != null)){
            edu_date[i] ="FROM <i>Unknow</i> TO <i>"+profile.educations.values[i].endDate.year+"</i>";
        }else if((profile.educations.values[i].endDate == null)&&(profile.educations.values[i].startDate != null)){
             edu_date[i] ="FROM <i>Unknow</i> TO <i>"+profile.educations.values[i].endDate.year+"</i>";
        }else if ((profile.educations.values[i].startDate != null)&&(profile.educations.values[i].endDate != null)){
            edu_date[i] ="FROM <i>"+profile.educations.values[i].startDate.year+"</i> TO <i>"+profile.educations.values[i].endDate.year+"</i>";
        }else{
            edu_date[i]="<i>Unknow</i>"
        }
        
        edu_degree[i] =profile.educations.values[i].degree;
        edu_activities[i] = profile.educations.values[i].activities;
        edu_notes[i] =profile.educations.values[i].notes;
    }
    //additional info
     interest = profile.interests;
    if((profile.dateOfBirth != null)){
        dateOfBirth = profile.dateOfBirth.day+"-"+profile.dateOfBirth.month+"-"+profile.dateOfBirth.year;
    }else{
    dateOfBirth = "<i>Unknow</i>"
    }
    var pictureUrl = profile.pictureUrl || "http://static02.linkedin.com/scds/common/u/img/icon/icon_no_photo_80x80.png";
    //profHTML = "<p><a href=\"" + profile.publicProfileUrl + "\">";
    profHTML = "<p><img src=\"" + pictureUrl + "\"></a>&nbsp";      
    profHTML = profHTML + first_name + " " +last_name + "</a><br> <a onclick=\"IN.User.logout(); return false;\">logout</a>";
    profHTML = profHTML + "<hr width=600px align='left'>";
    profHTML = profHTML + "<h2>EXPERIENCES</h2>";
    for(var i=0;i<j;i++){
        profHTML = profHTML + "<b>"+pos_title[i]+"</b><br>";
        profHTML = profHTML + pos_company[i]+"<br>";
        profHTML = profHTML + "DATE : "+pos_date[i]+"<br>";
        profHTML = profHTML + "SUMMARY : <div style='width:550px; padding-left:40px;'>"+pos_summary[i]+"</div>";
        profHTML = profHTML +"<br>";
    }
    profHTML = profHTML + "<hr width=600px align='left'>";
    profHTML = profHTML + "<h2>EDUCATION</h2>";
    for(var i=0;i<k;i++){
        profHTML = profHTML + "<b>"+edu_schoolName[i]+"</b><br>";
        profHTML = profHTML + "Field of Study : "+edu_fieldOfStudy[i]+"<br>";
        profHTML = profHTML + "DATE : "+edu_date[i]+"<br>";
        profHTML = profHTML + "Degree : "+edu_degree[i]+"<br>";
        profHTML = profHTML + "ACTIVITIES : <div style='width:550px; padding-left:40px;'>"+edu_activities[i]+"</div>";
        profHTML = profHTML + "NOTES : <div style='width:550px; padding-left:40px;'>"+edu_notes[i]+"</div>";
        profHTML = profHTML +"<br>";
    }
    profHTML = profHTML + "<hr width=600px align='left'>";
    profHTML = profHTML + "<h2>ADDITIONAL INFORMATION</h2>";
    profHTML = profHTML + "Interest : "+interest+"<br>";
    profHTMl = profHTML + "Date of Birth : "+dateOfBirth+"<br>";
    profHTML = profHTMl + "</p>";
  }
  document.getElementById("loginbadge").innerHTML = profHTML;
  document.getElementById("id").value = id;
  document.getElementById("first_name").value=first_name;
  document.getElementById("last_name").value = last_name;
  document.getElementById("interest").value = interest;
//  document.getElementById("j").value =j;
//  document.getElementById("j").submit();
}

</script>

<!-- need to be logged in to use; if not, offer a login button -->
<script type="IN/Login"></script>

<div id="loginbadge">
  <p>
     
  </p>
</div>

<!--<div style="float:left; padding-right:16px;"><?php //echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3>Hello, <?php //echo $this->zfcUserDisplayName() ?>!</h3>-->
<a href="<?php echo $this->url('zfcuser/logout') ?>">[Sign Out]</a>
<!--<div style="clear:both;"></div>-->

//<?php
//    $form = $this->form;
//    echo $form;
//    $form->setAtrribute('action',$this->url('user',array('action'=>'index')));
//    $form->prepare();
//    echo $this->form()->openTag($form);
//    echo $this->formRow($form->get('id'));
//    echo $this->formRow($form->get('first_name'));
//    echo $this->formRow($form->get('last_name'));
//    echo $this->formSubmit($form->get('submit'));
//    echo $this->form()->closeTag();
//?>
<form method="post" action='<?php echo $this->url("insertdb/insertdb");?>'>
Id:<input type="text" id="id" name="id">
first_name:<input type="text" id="first_name" name="first_name"><br>
last_name:<input type="text" id="last_name" name="last_name"><br>
<!--interest:<input type="text" id="interest"><br>-->
<input type="submit" value="Add">
</form>







































