<h2>Candidate</h2>
<table class="table">
<tr>
    <th>id</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th> </th>
</tr>
<?php foreach ($this->userdatas as $userdata) : ?>
<tr>
    <td><?php echo $this->escapeHtml($userdata->id);?></td>
    <td><?php echo $this->escapeHtml($userdata->first_name);?></td>
    <td><?php echo $this->escapeHtml($userdata->last_name);?></td>
    <td>
        <a href="<?php echo $this->url('showdetail',
            array('action'=>'showdetail', 'id' => $userdata->id));?>" target="_blank">Detail</a>
    </td>
</tr>

<?php endforeach; ?>
</table>