<?php
// module/Album/view/album/album/index.phtml:

$title = 'My Job';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('Job/add', array('action'=>'add'));?>">Add new job</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($jobs as $job) : ?>
<tr>
    <td><?php echo $this->escapeHtml($job->title);?></td>
    <td><?php echo $this->escapeHtml($job->artist);?></td>
    <td>
        <a href="<?php //echo $this->url('job/edit/2',array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php //echo $this->url('album/delete/4',array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
